"""remove_email_password_add_external_id_to_profile_user

Revision ID: 07a486e93cb1
Revises: 1ce7ebcd6977
Create Date: 2026-02-27 19:08:31.503038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07a486e93cb1"
down_revision: Union[str, Sequence[str], None] = "1ce7ebcd6977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("external_id", sa.Integer(), nullable=False), schema="profile"
    )
    op.drop_index(op.f("ix_profile_User_email"), table_name="User", schema="profile")
    op.create_index(
        op.f("ix_profile_User_external_id"),
        "User",
        ["external_id"],
        unique=True,
        schema="profile",
    )
    op.drop_column("User", "email", schema="profile")
    op.drop_column("User", "password", schema="profile")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "password", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        schema="profile",
    )
    op.add_column(
        "User",
        sa.Column("email", sa.VARCHAR(length=125), autoincrement=False, nullable=False),
        schema="profile",
    )
    op.drop_index(
        op.f("ix_profile_User_external_id"), table_name="User", schema="profile"
    )
    op.create_index(
        op.f("ix_profile_User_email"), "User", ["email"], unique=True, schema="profile"
    )
    op.drop_column("User", "external_id", schema="profile")
    # ### end Alembic commands ###
