"""initial_migration_with_all_models

Revision ID: 0918a17e6e4d
Revises: 
Create Date: 2026-02-11 10:51:34.691052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0918a17e6e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccessPolicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_table('Company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('LANGUAGE', 'TOOL', 'FRAMEWORK', name='SKILL_CATEGORY'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_index(op.f('ix_profile_User_email'), 'User', ['email'], unique=True, schema='profile')
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('Certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['profile.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.Column('degree', sa.String(length=25), nullable=False),
    sa.Column('field_of_study', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['profile.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['company_id'], ['profile.Company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Indica o tipo de link: Exemplo: SOCIAL_MEDIA, EMAIL, CELLPHONE'),
    sa.Column('from', sa.String(length=50), nullable=False, comment='Indica o local de origem. Exemplo: gmail, outlook, Linkedin, Instagram, etc...'),
    sa.Column('value', sa.String(length=150), nullable=False, comment='Indica o link na sua forma bruta. Exemplo: www.portfolio.com, 47988000554'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['profile.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=25), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=125), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['profile.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('Auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_token', sa.String(length=100), nullable=True),
    sa.Column('recovery_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('Session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('Achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['experience_id'], ['profile.Experience.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('CertificateSkills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['profile.Certificate.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['profile.Skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('EducationSkills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['education_id'], ['profile.Education.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['profile.Skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ExperienceSkills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['profile.Experience.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['profile.Skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ProfileCertificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['profile.Certificate.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.Profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ProfileEducation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['education_id'], ['profile.Education.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.Profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ProfileExperience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['profile.Experience.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.Profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ProfileLink',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['profile.Link.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.Profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('ProfileSkills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=False),
    sa.Column('last_used_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.Profile.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['profile.Skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProfileSkills', schema='profile')
    op.drop_table('ProfileLink', schema='profile')
    op.drop_table('ProfileExperience', schema='profile')
    op.drop_table('ProfileEducation', schema='profile')
    op.drop_table('ProfileCertificate', schema='profile')
    op.drop_table('ExperienceSkills', schema='profile')
    op.drop_table('EducationSkills', schema='profile')
    op.drop_table('CertificateSkills', schema='profile')
    op.drop_table('Achievements', schema='profile')
    op.drop_table('Session', schema='auth')
    op.drop_table('Auth', schema='auth')
    op.drop_table('Profile', schema='profile')
    op.drop_table('Link', schema='profile')
    op.drop_table('Experience', schema='profile')
    op.drop_table('Education', schema='profile')
    op.drop_table('Certificate', schema='profile')
    op.drop_table('User', schema='auth')
    op.drop_index(op.f('ix_profile_User_email'), table_name='User', schema='profile')
    op.drop_table('User', schema='profile')
    op.drop_table('Skill', schema='profile')
    op.drop_table('Company', schema='profile')
    op.drop_table('Role', schema='auth')
    op.drop_table('AccessPolicy', schema='auth')
    # ### end Alembic commands ###
