"""Add enterprise module

Revision ID: 1448ab8c1969
Revises: 61dc99c25bab
Create Date: 2026-03-08 22:40:33.994927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1448ab8c1969'
down_revision: Union[str, Sequence[str], None] = '61dc99c25bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('regional_classification', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('payment_periodicity', sa.String(length=25), nullable=False),
    sa.Column('min_payment_amount', sa.Numeric(), nullable=True),
    sa.Column('max_payment_amount', sa.Numeric(), nullable=True),
    sa.Column('is_payment_disclosed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=4), nullable=False),
    sa.Column('state', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('street', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('complement', sa.String(length=25), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Requirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Responsability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='enterprise'
    )
    op.create_table('CompanySegment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['enterprise.Company.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['enterprise.Segment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'segment_id', name='uq_company_segment'),
    schema='enterprise'
    )
    op.create_table('CompanyUnit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['enterprise.Company.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['enterprise.Location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'location_id', name='uq_company_unit'),
    schema='enterprise'
    )
    op.create_table('Vacancy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_unit_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('seniority_level', sa.String(length=25), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['company_unit_id'], ['enterprise.CompanyUnit.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['enterprise.Contract.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('Meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_version', sa.String(length=25), nullable=False),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsing_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['company_id'], ['enterprise.Company.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['enterprise.Vacancy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_meta_company'),
    sa.UniqueConstraint('vacancy_id', name='uq_meta_vacancy'),
    schema='enterprise'
    )
    op.create_table('VacancyRequirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('optional_requirement_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('experience_years', sa.SmallInteger(), nullable=True),
    sa.Column('requirement_type', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['optional_requirement_id'], ['enterprise.Requirement.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['enterprise.Requirement.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['enterprise.Vacancy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('VacancyResponsability',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('responsability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsability_id'], ['enterprise.Responsability.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['enterprise.Vacancy.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'responsability_id'),
    sa.UniqueConstraint('vacancy_id', 'responsability_id', name='uq_vacancy_responsability'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VacancyResponsability', schema='enterprise')
    op.drop_table('VacancyRequirement', schema='enterprise')
    op.drop_table('Meta', schema='enterprise')
    op.drop_table('Vacancy', schema='enterprise')
    op.drop_table('CompanyUnit', schema='enterprise')
    op.drop_table('CompanySegment', schema='enterprise')
    op.drop_table('Segment', schema='enterprise')
    op.drop_table('Responsability', schema='enterprise')
    op.drop_table('Requirement', schema='enterprise')
    op.drop_table('Location', schema='enterprise')
    op.drop_table('Contract', schema='enterprise')
    op.drop_table('Company', schema='enterprise')
    # ### end Alembic commands ###
