"""Add default soft delete and timestamp mixins to auth tables

Revision ID: 1ce7ebcd6977
Revises: 0918a17e6e4d
Create Date: 2026-02-12 15:20:36.926860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce7ebcd6977'
down_revision: Union[str, Sequence[str], None] = '0918a17e6e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AccessPolicy', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'), schema='auth')
    op.add_column('Auth', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'), schema='auth')
    op.add_column('Role', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'), schema='auth')
    op.add_column('Role', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'), schema='auth')
    op.add_column('Role', sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was last updated'), schema='auth')
    op.add_column('User', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when the record was soft deleted'), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'deleted_at', schema='auth')
    op.drop_column('Role', 'updated_at', schema='auth')
    op.drop_column('Role', 'created_at', schema='auth')
    op.drop_column('Role', 'deleted_at', schema='auth')
    op.drop_column('Auth', 'deleted_at', schema='auth')
    op.drop_column('AccessPolicy', 'deleted_at', schema='auth')
    # ### end Alembic commands ###
