"""Add timezone to DateTime columns and server defaults

Revision ID: cdf43b63f5ff
Revises: 07a486e93cb1
Create Date: 2026-03-08 13:42:39.107086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf43b63f5ff'
down_revision: Union[str, Sequence[str], None] = '07a486e93cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AccessPolicy', schema='auth')
    op.alter_column('Auth', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Auth', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('Auth', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Role', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('Role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('User', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.alter_column('User', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('User', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Achievements', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Certificate', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Company', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Education', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Experience', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Link', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Profile', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Skill', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('User', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Skill', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Profile', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Link', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Experience', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Education', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Company', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Certificate', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('Achievements', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='profile')
    op.alter_column('User', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('User', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('User', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Role', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Role', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('Role', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Auth', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True,
               schema='auth')
    op.alter_column('Auth', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was created',
               existing_nullable=False,
               schema='auth')
    op.alter_column('Auth', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True,
               schema='auth')
    op.create_table('AccessPolicy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the record was last updated'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id', name=op.f('AccessPolicy_pkey')),
    schema='auth'
    )
    # ### end Alembic commands ###
